### ISSUE TITLE
Dimension Error in `Listen`

### ISSUE THREAD

**Issue by RiskySignal** [hgstudent/las#4]
I think the dimension is not right in part `Listen`:
```
    x = pBLSTM( dim//2 )(input_1) # (..., audio_len//2, dim*2)
    x = pBLSTM( dim//2 )(x) # (..., audio_len//4, dim*2)
    x = pBLSTM( dim//4 )(x) # (..., audio_len//8, dim)
```
which I corrected as :
```
    x = pBLSTM( dim//2 )(input_1) # (..., audio_len//4, dim*2)
    x = pBLSTM( dim//2 )(x) # (..., audio_len//16, dim*2)
    x = pBLSTM( dim//4 )(x) # (..., audio_len//64, dim)
```
Is it right?

**Comment by ServerSideHannes** [comment]
No, I don't think that is correct.
At each step of pBLSTM we reduce the length by 2. 2^3 = 8. 

It might be confusing since we use Bi-directional LSTM witch given an input of (Length, features) will return (Length, 2*features), the feature vectors of both directions are concatenated. We reshape this output to (Length/2, 4*features).

**Comment by RiskySignal** [comment]
Oh! Yes, I see it. Thanks!

**Comment by RiskySignal** [comment]
It's not an Error.
